import 'package:flutter_test/flutter_test.dart';
import 'package:animals_tasks/features/home/data/models/dog_model.dart';
import 'package:animals_tasks/features/home/domain/entities/dog_entity.dart';
import 'package:animals_tasks/core/networking/api_constants.dart';

void main() {
  group(' DogModel.fromJson', () {
    group(' Valid JSON parsing', () {
      test('parses complete valid JSON correctly', () {
        final json = {
          'id': 'abys',
          'name': 'Abyssinian',
          'reference_image_id': '0XYvRd7oD',
          'weight': {'metric': '3 - 5'},
          'life_span': '14 - 15',
          'breed_group': 'Hound',
          'temperament': 'Gentle, Curious',
        };

        final model = DogModel.fromJson(json);

        expect(model.id, 'abys');
        expect(model.name, 'Abyssinian');
        expect(model.imageUrl, '${ApiPath.dogImageCdn}0XYvRd7oD.jpg');
        expect(model.weight, '3 - 5');
        expect(model.lifeSpan, '14 - 15');
        expect(model.breedGroup, 'Hound');
        expect(model.description, 'Gentle, Curious');
        expect(model.isFavorite, false); // Default value
        expect(model.gender, isNotNull); // Generated by helper
        expect(model.age, isNotNull); // Generated by helper
        expect(model.distance, isNotNull); // Generated by helper
      });

      test('parses JSON with minimal required fields', () {
        final json = {
          'id': 'simple',
          'name': 'Simple Dog',
          'reference_image_id': 'abc123',
        };

        final model = DogModel.fromJson(json);

        expect(model.id, 'simple');
        expect(model.name, 'Simple Dog');
        expect(model.imageUrl, '${ApiPath.dogImageCdn}abc123.jpg');
        expect(model.weight, '');
        expect(model.lifeSpan, '');
        expect(model.breedGroup, ''); // Returns empty string, not null
        expect(model.description, '');
      });

      test('constructs correct CDN URL from reference_image_id', () {
        final json = {
          'id': 'cdn',
          'name': 'CDN Test',
          'reference_image_id': 'XYZ789',
        };

        final model = DogModel.fromJson(json);

        expect(model.imageUrl, '${ApiPath.dogImageCdn}XYZ789.jpg');
        expect(model.imageUrl, contains('https://cdn2.thedogapi.com/images/'));
        expect(model.imageUrl, endsWith('.jpg'));
      });
    });

    group('Type conversion', () {
      test('converts int ID to string', () {
        final json = {
          'id': 123,
          'name': 'Numeric ID Dog',
          'reference_image_id': 'test',
        };

        final model = DogModel.fromJson(json);

        expect(model.id, '123');
        expect(model.id, isA<String>());
      });

      test('converts double ID to string', () {
        final json = {
          'id': 456.78,
          'name': 'Double ID Dog',
          'reference_image_id': 'test',
        };

        final model = DogModel.fromJson(json);

        expect(model.id, '456.78');
      });

      test('handles bool ID by converting to string', () {
        final json = {
          'id': true,
          'name': 'Bool ID Dog',
          'reference_image_id': 'test',
        };

        final model = DogModel.fromJson(json);

        expect(model.id, 'true');
      });
    });

    group(' Null and missing field handling', () {
      test('handles null ID gracefully', () {
        final json = {
          'id': null,
          'name': 'Null ID Dog',
          'reference_image_id': 'test',
        };

        final model = DogModel.fromJson(json);

        expect(model.id, '');
      });

      test('handles null name with default value', () {
        final json = {
          'id': 'no-name',
          'name': null,
          'reference_image_id': 'test',
        };

        final model = DogModel.fromJson(json);

        expect(model.name, 'Unknown Breed');
      });

      test('handles missing name with default value', () {
        final json = {
          'id': 'no-name-2',
          'reference_image_id': 'test',
        };

        final model = DogModel.fromJson(json);

        expect(model.name, 'Unknown Breed');
      });

      test('handles null reference_image_id with empty string', () {
        final json = {
          'id': 'noimg',
          'name': 'No Image Dog',
          'reference_image_id': null,
        };

        final model = DogModel.fromJson(json);

        expect(model.imageUrl, '');
      });

      test('handles missing reference_image_id with empty string', () {
        final json = {
          'id': 'noimg2',
          'name': 'No Image Dog 2',
        };

        final model = DogModel.fromJson(json);

        expect(model.imageUrl, '');
      });

      test('handles null weight map', () {
        final json = {
          'id': 'test',
          'name': 'Test',
          'weight': null,
        };

        final model = DogModel.fromJson(json);

        expect(model.weight, '');
      });

      test('handles missing weight field', () {
        final json = {
          'id': 'test',
          'name': 'Test',
        };

        final model = DogModel.fromJson(json);

        expect(model.weight, '');
      });

      test('handles null life_span', () {
        final json = {
          'id': 'test',
          'name': 'Test',
          'life_span': null,
        };

        final model = DogModel.fromJson(json);

        expect(model.lifeSpan, '');
      });

      test('handles null breed_group', () {
        final json = {
          'id': 'test',
          'name': 'Test',
          'breed_group': null,
        };

        final model = DogModel.fromJson(json);

        expect(model.breedGroup, '');
      });

      test('handles null temperament', () {
        final json = {
          'id': 'test',
          'name': 'Test',
          'temperament': null,
        };

        final model = DogModel.fromJson(json);

        expect(model.description, '');
      });

      test('handles completely empty JSON', () {
        final json = <String, dynamic>{};

        final model = DogModel.fromJson(json);

        expect(model.id, '');
        expect(model.name, 'Unknown Breed');
        expect(model.imageUrl, '');
        expect(model.weight, '');
        expect(model.lifeSpan, '');
        expect(model.breedGroup, '');
        expect(model.description, '');
      });
    });

    group('🐛 Invalid data handling', () {
      test('handles invalid weight type (string instead of map)', () {
        final json = {
          'id': 'err',
          'name': 'Bad Weight Dog',
          'reference_image_id': 'abc',
          'weight': 'not_a_map',
        };

        // This will throw because the code tries to access ['metric'] on a string
        expect(() => DogModel.fromJson(json), throwsA(isA<TypeError>()));
      });

      test('handles invalid weight map without metric key', () {
        final json = {
          'id': 'err',
          'name': 'No Metric Dog',
          'reference_image_id': 'abc',
          'weight': {'imperial': '10 - 15'},
        };

        final model = DogModel.fromJson(json);

        expect(model.weight, '');
      });

      test('handles weight map with null metric value', () {
        final json = {
          'id': 'err',
          'name': 'Null Metric Dog',
          'reference_image_id': 'abc',
          'weight': {'metric': null},
        };

        final model = DogModel.fromJson(json);

        expect(model.weight, '');
      });

      test('handles empty string values', () {
        final json = {
          'id': '',
          'name': '',
          'reference_image_id': '',
          'weight': {'metric': ''},
          'life_span': '',
          'breed_group': '',
          'temperament': '',
        };

        final model = DogModel.fromJson(json);

        expect(model.id, '');
        expect(model.name, ''); // Empty string is passed through
        expect(model.imageUrl, '${ApiPath.dogImageCdn}.jpg');
        expect(model.weight, '');
        expect(model.lifeSpan, '');
        expect(model.breedGroup, '');
        expect(model.description, '');
      });
    });

    group('🎲 Random helper methods', () {
      test('generates valid gender values', () {
        // Run multiple times to test randomness
        final genders = <String>{};
        for (var i = 0; i < 100; i++) {
          final json = {
            'id': 'test$i',
            'name': 'Test Dog $i',
          };
          final model = DogModel.fromJson(json);
          genders.add(model.gender!);
        }

        // Should generate at least one gender value
        expect(genders, isNotEmpty);
        // All values should be either Male or Female
        expect(genders.every((g) => g == 'Male' || g == 'Female'), isTrue);
        expect(genders.length, lessThanOrEqualTo(2));
      });

      test('generates valid age values', () {
        final ages = <String>{};
        final validAges = {'3 Months Old', '1 Year', '2 Years', '5 Months Old'};

        for (var i = 0; i < 200; i++) {
          final json = {
            'id': 'test$i',
            'name': 'Test Dog $i',
          };
          final model = DogModel.fromJson(json);
          ages.add(model.age!);
        }

        // Should generate at least one age value
        expect(ages, isNotEmpty);
        // All generated ages should be in valid set
        expect(ages.every((a) => validAges.contains(a)), isTrue);
        expect(ages.length, lessThanOrEqualTo(4));
      });

      test('generates valid distance values', () {
        final distances = <String>{};
        final validDistances = {'1.6 km away', '2.7 km away', '3 km away'};

        for (var i = 0; i < 150; i++) {
          final json = {
            'id': 'test$i',
            'name': 'Test Dog $i',
          };
          final model = DogModel.fromJson(json);
          distances.add(model.distance!);
        }

        // Should generate at least one distance value
        expect(distances, isNotEmpty);
        // All generated distances should be in valid set
        expect(distances.every((d) => validDistances.contains(d)), isTrue);
        expect(distances.length, lessThanOrEqualTo(3));
      });

      test('always generates non-null gender, age, and distance', () {
        final validGenders = {'Male', 'Female'};
        final validAges = {'3 Months Old', '1 Year', '2 Years', '5 Months Old'};
        final validDistances = {'1.6 km away', '2.7 km away', '3 km away'};

        for (var i = 0; i < 50; i++) {
          final json = {
            'id': 'test$i',
            'name': 'Test Dog $i',
          };
          final model = DogModel.fromJson(json);

          expect(model.gender, isNotNull);
          expect(model.age, isNotNull);
          expect(model.distance, isNotNull);
          expect(model.gender, isNotEmpty);
          expect(model.age, isNotEmpty);
          expect(model.distance, isNotEmpty);

          // Verify values are from valid sets
          expect(validGenders.contains(model.gender), isTrue);
          expect(validAges.contains(model.age), isTrue);
          expect(validDistances.contains(model.distance), isTrue);
        }
      });
    });
  });

  group('🐾 DogModel.toEntity', () {
    test('converts complete model to entity correctly', () {
      final model = DogModel(
        id: '1',
        name: 'Tom',
        imageUrl: 'https://example.com/image.jpg',
        gender: 'Male',
        age: '2 Years',
        weight: '4 - 6',
        distance: '1.6 km away',
        lifeSpan: '10 - 12',
        breedGroup: 'Hound',
        description: 'Friendly and loyal',
        isFavorite: true,
      );

      final entity = model.toEntity();

      expect(entity, isA<DogEntity>());
      expect(entity.id, '1');
      expect(entity.name, 'Tom');
      expect(entity.imageUrl, 'https://example.com/image.jpg');
      expect(entity.gender, 'Male');
      expect(entity.age, '2 Years');
      expect(entity.weight, '4 - 6');
      expect(entity.distance, '1.6 km away');
      expect(entity.lifeSpan, '10 - 12');
      expect(entity.breedGroup, 'Hound');
      expect(entity.description, 'Friendly and loyal');
      expect(entity.isFavorite, true);
    });

    test('converts model with null optional fields', () {
      final model = DogModel(
        id: '2',
        name: 'Rex',
        imageUrl: 'https://example.com/rex.jpg',
      );

      final entity = model.toEntity();

      expect(entity.id, '2');
      expect(entity.name, 'Rex');
      expect(entity.imageUrl, 'https://example.com/rex.jpg');
      expect(entity.gender, isNull);
      expect(entity.age, isNull);
      expect(entity.weight, isNull);
      expect(entity.distance, isNull);
      expect(entity.lifeSpan, isNull);
      expect(entity.breedGroup, isNull);
      expect(entity.description, isNull);
      expect(entity.isFavorite, false);
    });

    test('preserves all field values during conversion', () {
      final model = DogModel(
        id: '3',
        name: 'Buddy',
        imageUrl: 'https://example.com/buddy.jpg',
        gender: 'Female',
        age: '5 Months Old',
        weight: '2 - 3',
        distance: '3 km away',
        lifeSpan: '12 - 14',
        breedGroup: 'Toy',
        description: 'Playful and energetic',
        isFavorite: false,
      );

      final entity = model.toEntity();

      // Verify no data loss during conversion
      expect(entity.id, model.id);
      expect(entity.name, model.name);
      expect(entity.imageUrl, model.imageUrl);
      expect(entity.gender, model.gender);
      expect(entity.age, model.age);
      expect(entity.weight, model.weight);
      expect(entity.distance, model.distance);
      expect(entity.lifeSpan, model.lifeSpan);
      expect(entity.breedGroup, model.breedGroup);
      expect(entity.description, model.description);
      expect(entity.isFavorite, model.isFavorite);
    });

    test('converts model with empty strings correctly', () {
      final model = DogModel(
        id: '',
        name: '',
        imageUrl: '',
        gender: '',
        age: '',
        weight: '',
        distance: '',
        lifeSpan: '',
        breedGroup: '',
        description: '',
      );

      final entity = model.toEntity();

      expect(entity.id, '');
      expect(entity.name, '');
      expect(entity.imageUrl, '');
      expect(entity.gender, '');
      expect(entity.age, '');
      expect(entity.weight, '');
      expect(entity.distance, '');
      expect(entity.lifeSpan, '');
      expect(entity.breedGroup, '');
      expect(entity.description, '');
    });

    test('entity remains independent after model changes', () {
      var model = const DogModel(
        id: '4',
        name: 'Max',
        imageUrl: 'https://example.com/max.jpg',
      );

      final entity = model.toEntity();

      // Create a new model (since DogModel is const/immutable)
      model = const DogModel(
        id: '5',
        name: 'Charlie',
        imageUrl: 'https://example.com/charlie.jpg',
      );

      // Entity should still have original values
      expect(entity.id, '4');
      expect(entity.name, 'Max');
      expect(entity.imageUrl, 'https://example.com/max.jpg');
    });
  });

  group('🔒 DogModel immutability', () {
    test('creates instances with const constructor', () {
      const model1 = DogModel(
        id: '1',
        name: 'Test',
        imageUrl: 'test.jpg',
      );
      const model2 = DogModel(
        id: '1',
        name: 'Test',
        imageUrl: 'test.jpg',
      );

      expect(identical(model1, model2), isTrue);
    });

    test('has immutable fields', () {
      final model = DogModel(
        id: '1',
        name: 'Test',
        imageUrl: 'test.jpg',
      );

      // All fields should be final (this is compile-time checked)
      expect(model.id, '1');
      expect(model.name, 'Test');
      expect(model.imageUrl, 'test.jpg');
    });
  });

  group('🧪 Integration tests', () {
    test('fromJson followed by toEntity preserves data', () {
      final json = {
        'id': 'integration',
        'name': 'Integration Dog',
        'reference_image_id': 'int123',
        'weight': {'metric': '10 - 12'},
        'life_span': '10 - 15',
        'breed_group': 'Working',
        'temperament': 'Loyal, Brave',
      };

      final model = DogModel.fromJson(json);
      final entity = model.toEntity();

      expect(entity.id, 'integration');
      expect(entity.name, 'Integration Dog');
      expect(entity.imageUrl, contains('int123'));
      expect(entity.weight, '10 - 12');
      expect(entity.lifeSpan, '10 - 15');
      expect(entity.breedGroup, 'Working');
      expect(entity.description, 'Loyal, Brave');
      expect(entity.gender, isNotNull);
      expect(entity.age, isNotNull);
      expect(entity.distance, isNotNull);
    });

    test('handles real API response structure', () {
      // Simulating a real Dog API response
      final json = {
        'id': 230,
        'name': 'Poodle',
        'bred_for': 'Retrieving, Companionship',
        'breed_group': 'Non-Sporting',
        'life_span': '12 - 15 years',
        'temperament':
            'Intelligent, Active, Alert, Faithful, Trainable, Instinctual',
        'reference_image_id': 'HByGhh8Ix',
        'weight': {'imperial': '45 - 70', 'metric': '20 - 32'},
        'height': {'imperial': '15 - 22', 'metric': '38 - 56'},
      };

      final model = DogModel.fromJson(json);

      expect(model.id, '230');
      expect(model.name, 'Poodle');
      expect(model.breedGroup, 'Non-Sporting');
      expect(model.lifeSpan, '12 - 15 years');
      expect(model.description, contains('Intelligent'));
      expect(model.imageUrl, '${ApiPath.dogImageCdn}HByGhh8Ix.jpg');
      expect(model.weight, '20 - 32');
    });

    test('handles API response with missing optional fields', () {
      final json = {
        'id': 100,
        'name': 'Mixed Breed',
        'reference_image_id': 'mixed123',
      };

      final model = DogModel.fromJson(json);
      final entity = model.toEntity();

      expect(entity.id, '100');
      expect(entity.name, 'Mixed Breed');
      expect(entity.imageUrl, isNotEmpty);
      expect(entity.breedGroup, anyOf(isNull, isEmpty));
      expect(entity.lifeSpan, anyOf(isNull, isEmpty));
    });
  });
}
